prompt_root_dir: './prompts'
image_size_h: 480
image_size_w: 640
image_crop: [30, 50, 400, 540]
#image_crop: [0, 0, 480, 640]

grounding:
  prompt_name: 'ocid/referring_segmentation.txt'
  prompt_template: "Description: {user_input}"

  include_raw_image: True

  use_subplot_prompt: True
  subplot_size: 448
  
  do_refine_marks: False
  refine_marks:
    maximum_hole_area: 0.01
    maximum_island_area: 0.01
    minimum_mask_area: 0.02
    maximum_mask_area: 1.0

  do_inctx: False
  inctx_prompt_name: null

  visualizer:
    label:
      text_include: True
      text_scale: 0.6
      text_thickness: 2
      text_padding: 3
      text_position: 'CENTER_OF_MASS'
    box:
      box_include: False
      box_thickness: 2
    mask:
      mask_include: True
      mask_opacity: 0.25
    polygon:
      polygon_include: True
      polygon_thickness: 2

  request:
    model_name: 'gpt-4o'
    detail: 'auto'
    temperature: 0.00000001
    n: 1
    max_tokens: 512
    seed: 12


planning:
  prompt_name: 'ocid/grasp_planning.txt'
  prompt_template: 'Task instruction: "Grasp object {user_input}".'
  response_format: 'json'

  include_raw_image: False

  use_subplot_prompt: False
  subplot_size: 448
  
  do_refine_marks: False
  refine_marks:
    maximum_hole_area: 0.01
    maximum_island_area: 0.01
    minimum_mask_area: 0.02
    maximum_mask_area: 1.0

  do_inctx: False
  inctx_prompt_name: 'ocid/inctx_grasp_planning.pt'

  visualizer:
    label:
      text_include: True
      text_scale: 0.8
      text_thickness: 2
      text_padding: 3
      text_position: 'CENTER_OF_MASS'
    box:
      box_include: False
      box_thickness: 2
    mask:
      mask_include: True
      mask_opacity: 0.3
    polygon:
      polygon_include: True
      polygon_thickness: 3

  request:
    model_name: 'gpt-4o'
    detail: 'auto'
    temperature: 0.0
    n: 1
    max_tokens: 256


grasping:
  crop_square_size: 224

  prompt_name: 'ocid/grasp_ranking.txt'
  prompt_template: "Rank the grasp poses."

  use_subplot_prompt: True
  subplot_size: 448

  do_inctx: False
  inctx_prompt_name: 'ocid/inctx_grasp_ranking.pt'

  visualizer:
    as_line: True
    line_thickness: 8
    grasp_colors: 'red,green'
    with_gray: False
    label:
      label_include: False
      text_color: 'white'
      text_rect_color: 'black'
      text_padding: 2
      text_thickness: 1
      text_scale: 0.7
      text_position: 'CENTER'
    box:
      box_include: False
      box_color: 'red'
      box_thickness: 2
    mask:
      mask_include: False
      mask_color: 'red'
      mask_opacity: 0.15
    polygon:
      polygon_include: True
      polygon_color: 'red'
      polygon_thickness: 3

  request:
    model_name: 'gpt-4o'
    detail: 'auto'
    temperature: 0.0
    n: 1
    max_tokens: 4096
